import type { CSSProperties } from 'react';

export const sharedStyles: Record<string, CSSProperties> = {
  pageShell: {
    minHeight: '100vh',
    background: '#172033',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
  },
  phoneCanvas: {
    background: '#f6f2ea',
    minHeight: '100vh',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
    maxWidth: 520,
  },
  subPageHeader: {
    alignItems: 'center',
    background: 'linear-gradient(135deg, #172033 0%, #26364f 58%, #445a7c 100%)',
    color: '#ffffff',
    display: 'flex',
    gap: 12,
    padding: '18px 16px 22px',
  },
  backButton: {
    background: 'rgba(255, 255, 255, 0.12)',
    border: '1px solid rgba(255, 255, 255, 0.16)',
    borderRadius: 999,
    color: '#ffffff',
    cursor: 'pointer',
    flexShrink: 0,
    fontSize: 14,
    fontWeight: 900,
    padding: '10px 14px',
  },
  subPageTitle: {
    color: '#ffffff',
    flex: 1,
    fontSize: 26,
    fontWeight: 900,
    letterSpacing: -0.5,
    margin: 0,
  },
  subPageContent: {
    padding: '16px 16px 28px',
  },
  floatingBackButton: {
    background: 'rgba(255, 255, 255, 0.92)',
    border: 0,
    borderRadius: 999,
    color: '#172033',
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 900,
    left: 16,
    padding: '11px 14px',
    position: 'absolute',
    top: 18,
  },
  detailsTopImageWrap: {
    height: 380,
    position: 'relative',
  },
  detailsTopImage: {
    display: 'block',
    height: '100%',
    objectFit: 'cover',
    width: '100%',
  },
  detailsSheet: {
    background: '#f6f2ea',
    borderRadius: '34px 34px 0 0',
    boxShadow: '0 -18px 42px rgba(0, 0, 0, 0.18)',
    marginTop: -36,
    minHeight: 'calc(100vh - 344px)',
    padding: '24px 18px 30px',
    position: 'relative',
  },
  detailsType: {
    color: '#f09d18',
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: 1.2,
    margin: '0 0 6px',
    textTransform: 'uppercase',
  },
  detailsName: {
    color: '#172033',
    fontSize: 42,
    fontWeight: 900,
    letterSpacing: -1.2,
    lineHeight: 1,
    margin: 0,
  },
  detailsDescription: {
    color: '#5f5548',
    fontSize: 16,
    lineHeight: 1.55,
    margin: '16px 0 0',
  },
  detailsInfoRow: {
    display: 'grid',
    gap: 10,
    gridTemplateColumns: '1fr 1fr',
    marginTop: 18,
  },
  detailsInfoItem: {
    background: '#ffffff',
    border: '1px solid #eadfce',
    borderRadius: 20,
    padding: 14,
  },
  infoSmallLabel: {
    color: '#736959',
    display: 'block',
    fontSize: 12,
    fontWeight: 900,
    marginBottom: 4,
  },
  infoStrong: {
    color: '#172033',
    fontSize: 14,
  },
  primaryButton: {
    background: '#172033',
    border: 0,
    borderRadius: 20,
    color: '#ffffff',
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 900,
    marginTop: 22,
    padding: '16px 18px',
    width: '100%',
  },
  searchBox: {
    alignItems: 'center',
    background: '#ffffff',
    border: '1px solid #eadfce',
    borderRadius: 22,
    boxShadow: '0 10px 25px rgba(54, 42, 27, 0.08)',
    display: 'flex',
    gap: 10,
    padding: '0 14px',
  },
  searchIcon: {
    color: '#8a7d6d',
    fontSize: 24,
    fontWeight: 900,
  },
  searchInput: {
    background: 'transparent',
    border: 0,
    color: '#172033',
    flex: 1,
    fontSize: 15,
    outline: 'none',
    padding: '15px 0',
  },
  filterRow: {
    display: 'grid',
    gap: 10,
    gridTemplateColumns: '1fr 1fr',
    marginTop: 12,
  },
  selectControl: {
    background: '#ffffff',
    border: '1px solid #eadfce',
    borderRadius: 16,
    color: '#172033',
    fontSize: 14,
    fontWeight: 700,
    padding: '12px 14px',
    width: '100%',
  },
  card: {
    background: '#ffffff',
    border: '1px solid #eadfce',
    borderRadius: 24,
    boxShadow: '0 14px 28px rgba(54, 42, 27, 0.09)',
    cursor: 'pointer',
    overflow: 'hidden',
  },
  cardImage: {
    display: 'block',
    height: 150,
    objectFit: 'cover',
    width: '100%',
  },
  cardBody: {
    display: 'grid',
    gap: 8,
    padding: 14,
  },
  cardTitle: {
    color: '#172033',
    fontSize: 20,
    fontWeight: 900,
    margin: 0,
  },
  cardText: {
    color: '#736959',
    fontSize: 14,
    lineHeight: 1.45,
    margin: 0,
  },
  cardMeta: {
    color: '#465872',
    fontSize: 13,
    fontWeight: 900,
    margin: 0,
  },
  cardsList: {
    display: 'grid',
    gap: 14,
    marginTop: 16,
  },
  emptyState: {
    background: '#ffffff',
    borderRadius: 22,
    display: 'grid',
    gap: 5,
    marginTop: 16,
    padding: 20,
    textAlign: 'center',
  },
  emptyTitle: {
    color: '#172033',
    fontSize: 17,
    fontWeight: 900,
  },
  emptyText: {
    color: '#736959',
    fontSize: 14,
  },
  placeholderBox: {
    alignItems: 'center',
    background: '#ffffff',
    border: '2px dashed #cfc6b6',
    borderRadius: 22,
    color: '#736959',
    display: 'flex',
    fontSize: 14,
    fontWeight: 700,
    justifyContent: 'center',
    marginTop: 16,
    minHeight: 140,
    padding: 18,
    textAlign: 'center',
  },
  sectionTitle: {
    color: '#172033',
    fontSize: 20,
    fontWeight: 900,
    margin: '22px 0 10px',
  },
  spaceRow: {
    alignItems: 'center',
    background: '#ffffff',
    border: '1px solid #eadfce',
    borderRadius: 20,
    display: 'grid',
    gap: 10,
    gridTemplateColumns: '1fr auto',
    padding: '14px 14px 14px 16px',
  },
  spaceRowInfo: {
    display: 'grid',
    gap: 4,
  },
  spaceRowTitle: {
    color: '#172033',
    fontSize: 17,
    fontWeight: 900,
    margin: 0,
  },
  spaceRowMeta: {
    color: '#736959',
    fontSize: 13,
    fontWeight: 700,
    margin: 0,
  },
  secondaryButton: {
    background: '#f9b54a',
    border: 0,
    borderRadius: 14,
    color: '#172033',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 900,
    padding: '10px 12px',
    whiteSpace: 'nowrap',
  },
  popupOverlay: {
    alignItems: 'center',
    background: 'rgba(8, 13, 24, 0.68)',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    padding: 18,
    position: 'fixed',
    zIndex: 100,
  },
  popupBox: {
    background: '#ffffff',
    borderRadius: 28,
    boxShadow: '0 20px 45px rgba(0, 0, 0, 0.28)',
    maxWidth: 420,
    padding: 18,
    width: '100%',
  },
  popupTitle: {
    color: '#172033',
    fontSize: 24,
    fontWeight: 900,
    margin: '0 0 12px',
    textAlign: 'center',
  },
  popupImage: {
    borderRadius: 20,
    display: 'block',
    height: 230,
    objectFit: 'cover',
    width: '100%',
  },
  closeButton: {
    background: '#172033',
    border: 0,
    borderRadius: 18,
    color: '#ffffff',
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 900,
    marginTop: 16,
    padding: '13px 14px',
    width: '100%',
  },
};
