spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/feri_navigator}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:feri}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:feri}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.open-in-view=false
