spring.application.name=feri-navigator

# Database — vrednosti dolaze iz Docker Compose env varijabli
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:feri_navigator}
spring.datasource.username=${DB_USERNAME:feri}
spring.datasource.password=${DB_PASSWORD:feri}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false

# Server
server.port=8080
